#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* Generated by Rcpp's compileAttributes() function.
   These declarations are automatically updated when functions are added or modified.
   Do not edit manually. */

extern SEXP _punycoder_puny_encode_cpp(SEXP, SEXP);
extern SEXP _punycoder_puny_decode_cpp(SEXP, SEXP);
extern SEXP _punycoder_url_encode_cpp(SEXP, SEXP);
extern SEXP _punycoder_url_decode_cpp(SEXP, SEXP);
extern SEXP _punycoder_parse_url_cpp(SEXP, SEXP);
extern SEXP _punycoder_validate_domain_cpp(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_punycoder_puny_encode_cpp", (DL_FUNC) &_punycoder_puny_encode_cpp, 2},
    {"_punycoder_puny_decode_cpp", (DL_FUNC) &_punycoder_puny_decode_cpp, 2},
    {"_punycoder_url_encode_cpp", (DL_FUNC) &_punycoder_url_encode_cpp, 2},
    {"_punycoder_url_decode_cpp", (DL_FUNC) &_punycoder_url_decode_cpp, 2},
    {"_punycoder_parse_url_cpp", (DL_FUNC) &_punycoder_parse_url_cpp, 2},
    {"_punycoder_validate_domain_cpp", (DL_FUNC) &_punycoder_validate_domain_cpp, 2},
    {NULL, NULL, 0}
};

void R_init_punycoder(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}

