// Generated by data-raw/generate_unicode_tables.R. DO NOT EDIT BY HAND.
// Unicode 16.0.0. Accessors for NFC + UTS-46 used by canonical-host normalization.
#ifndef PUNYCODER_UNICODE_TABLES_16_0_0_H
#define PUNYCODER_UNICODE_TABLES_16_0_0_H

#include <cstddef>
#include <cstdint>

namespace punycoder {
namespace u16 {

extern const char *const UNICODE_VERSION;

enum class IdnaStatus : uint8_t {
  valid = 0,
  ignored = 1,
  mapped = 2,
  deviation = 3,
  disallowed = 4,
  disallowed_std3_valid = 5,
  disallowed_std3_mapped = 6
};

// Canonical combining class of cp (0 if unlisted).
uint8_t combining_class(uint32_t cp);

// Full canonical decomposition of cp (recursively expanded, excluding Hangul).
// Returns a pointer to len code points, or nullptr with len = 0 if none.
const uint32_t *canonical_decomposition(uint32_t cp, uint32_t &len);

// Primary canonical composition of starter a and combiner b; 0 if none.
uint32_t canonical_compose(uint32_t a, uint32_t b);

// UTS-46 status of cp. If the status is mapped, deviation, or
// disallowed_std3_mapped and a mapping exists, sets map/len to the target
// sequence (len may be 0 for an empty mapping). Unlisted code points are
// disallowed.
IdnaStatus idna_lookup(uint32_t cp, const uint32_t *&map, uint32_t &len);

// True if cp has general category Mn, Mc, or Me (UTS-46 rule V5).
bool is_combining_mark(uint32_t cp);

}  // namespace u16
}  // namespace punycoder

#endif  // PUNYCODER_UNICODE_TABLES_16_0_0_H

